-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Guess" ADD COLUMN     "guessedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
